// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Entity.Entity
{
    public partial class CommonmoviesapplicationContext : DbContext
    {
        public CommonmoviesapplicationContext()
        {
        }

        public CommonmoviesapplicationContext(DbContextOptions<CommonmoviesapplicationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FavouriteMovie> FavouriteMovies { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<SearchedMovie> SearchedMovies { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Turkish_CI_AS");

            modelBuilder.Entity<Movie>(entity =>
            {
                entity.Property(e => e.Actors).IsUnicode(false);

                entity.Property(e => e.Awards).IsUnicode(false);

                entity.Property(e => e.Country).IsUnicode(false);

                entity.Property(e => e.Director).IsUnicode(false);

                entity.Property(e => e.Genre).IsUnicode(false);

                entity.Property(e => e.ImdbId).IsUnicode(false);

                entity.Property(e => e.ImdbRating).IsUnicode(false);

                entity.Property(e => e.ImdbVotes).IsUnicode(false);

                entity.Property(e => e.Language).IsUnicode(false);

                entity.Property(e => e.Plot).IsUnicode(false);

                entity.Property(e => e.Poster).IsUnicode(false);

                entity.Property(e => e.Rated).IsUnicode(false);

                entity.Property(e => e.Released).IsUnicode(false);

                entity.Property(e => e.Runtime).IsUnicode(false);

                entity.Property(e => e.Title).IsUnicode(false);

                entity.Property(e => e.Type).IsUnicode(false);

                entity.Property(e => e.Writer).IsUnicode(false);

                entity.Property(e => e.Year).IsUnicode(false);
            });

            modelBuilder.Entity<Request>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.BirthYear).IsUnicode(false);

                entity.Property(e => e.Email).IsUnicode(false);

                entity.Property(e => e.Name).IsUnicode(false);

                entity.Property(e => e.Nickname).IsUnicode(false);

                entity.Property(e => e.Password).IsUnicode(false);

                entity.Property(e => e.Surname).IsUnicode(false);

                entity.Property(e => e.Tc).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}