// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entity.Entity
{
    [Table("Movie")]
    public partial class Movie
    {
        [Key]
        public int Id { get; set; }
        [Column("imdbId")]
        [StringLength(20)]
        public string ImdbId { get; set; }
        [Column("imdbVotes")]
        [StringLength(10)]
        public string ImdbVotes { get; set; }
        [Column("imdbRating")]
        [StringLength(5)]
        public string ImdbRating { get; set; }
        [StringLength(10)]
        public string Type { get; set; }
        [StringLength(300)]
        public string Title { get; set; }
        [StringLength(5)]
        public string Year { get; set; }
        [StringLength(10)]
        public string Rated { get; set; }
        [StringLength(30)]
        public string Released { get; set; }
        [StringLength(20)]
        public string Runtime { get; set; }
        [StringLength(100)]
        public string Genre { get; set; }
        [StringLength(100)]
        public string Director { get; set; }
        [StringLength(250)]
        public string Writer { get; set; }
        [StringLength(250)]
        public string Actors { get; set; }
        [StringLength(250)]
        public string Plot { get; set; }
        [StringLength(50)]
        public string Language { get; set; }
        [StringLength(10)]
        public string Country { get; set; }
        [StringLength(100)]
        public string Awards { get; set; }
        [StringLength(300)]
        public string Poster { get; set; }
    }
}