// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entity.Entity
{
    [Table("User")]
    public partial class User
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Surname { get; set; }
        [StringLength(50)]
        public string Nickname { get; set; }
        [StringLength(250)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [Column("TC")]
        [StringLength(11)]
        public string Tc { get; set; }
        [StringLength(4)]
        public string BirthYear { get; set; }
    }
}